require:
   - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
    - 'storage/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'config/**/*'
    - 'log/*'
    - 'test/**/*'